# Generated by Django 4.2.5 on 2024-12-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="level",
            field=models.CharField(default="beginner", max_length=50),
        ),
    ]
