# Generated by Django 4.2.5 on 2024-12-22 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_userresult_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
