# Generated by Django 4.2.5 on 2024-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_userresult_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="topic",
            field=models.CharField(
                choices=[
                    ("os", "Operating Systems"),
                    ("dbms", "Database Management Systems"),
                    ("dsa", "Data Structures & Algorithms"),
                    ("networks", "Networks"),
                    ("cloud", "Cloud Computing"),
                ],
                max_length=50,
            ),
        ),
    ]
